-- AlterTable
ALTER TABLE "Voters" ALTER COLUMN "houseHoldId" DROP DEFAULT,
ALTER COLUMN "newBatchDraftId" DROP DEFAULT,
ALTER COLUMN "precintsId" DROP DEFAULT,
ALTER COLUMN "teamLeaderId" DROP DEFAULT;
